apiVersion: v1
kind: ConfigMap
metadata:
  name: frontendmap
  #namespace: ui
data:
    NODE_ENV: DEV 
    REACT_APP_BACKEND_URL: "http://http://ac00b20cbf6d211e9b1b50ed95fc5aa0-786762308.us-east-1.elb.amazonaws.com" 


