apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: backend-role-binding
 namespace: default
subjects:
- kind: ServiceAccount
  name: backend-serviceaccount
  namespace: default
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
