apiVersion: v1
kind: ConfigMap
metadata:
  name: map
  #namespace: api
data:
    NODE_ENV: DEV
    PORT: "8080"
    SALT_ROUNDS: "10"
    DB_HOST: "csye7374-rds-instance.ctglp6wapayx.us-east-1.rds.amazonaws.com"
    DB_USER: "postgres1"
    DB_PASS: "csye7374"
    DB_PORT: "5432"
    DB_NAME: "csye7374"
    BUCKET_NAME: "prod-csye7374-recipe-image"
    AWS_ACCESS_KEY_ID: "AKIA4XKXXXXXXXXXX"
    SECRET_ACCESS_KEY_ID: "bUOFruvCZZ2Y8elwXXXXXXXXXXXXXXX"
    ELASTIC_HOST: "dns-host-name-of-your-elasticsearch-loadbalancer:9200"
