---
# tasks file for delete-deployment-backend
- name: Delete API namespace
  k8s:
    name: api
    api_version: v1
    #kubeconfig: /Users/akashbalani/Documents/assignment6-infra/team6-infra/frontend/frontend-ConfigMap.yaml
    #resource_definition: "{{ lookup('file', '/Users/akashbalani/Documents/assignment6-infra/team6-infra/frontend/frontend-ConfigMap.yaml') }}"
    kind: Namespace
#    state: absent
    state: absent
