apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-11-23T00:50:59Z
  generation: 1
  name: dev.csye6225-fall2018-sahanip.xyz
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "autoscaling:DescribeAutoScalingGroups",
            "autoscaling:DescribeAutoScalingInstances",
            "autoscaling:SetDesiredCapacity",
            "autoscaling:DescribeLaunchConfigurations",
            "autoscaling:DescribeTags",
            "autoscaling:TerminateInstanceInAutoScalingGroup"
          ],
          "Resource": ["*"]
        }
      ]
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://psdev-csye7374-kubernetes-cluster-state-store/dev.csye6225-fall2018-sahanip.xyz
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    - instanceGroup: master-us-east-1d
      name: d
    memoryRequest: 100Mi
    name: main
    version: 3.2.24
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    - instanceGroup: master-us-east-1d
      name: d
    memoryRequest: 100Mi
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook

  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.13.1
  masterInternalName: api.internal.dev.csye6225-fall2018-sahanip.xyz
  masterPublicName: api.dev.csye6225-fall2018-sahanip.xyz
  networkCIDR: 172.20.0.0/16
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.20.64.0/19
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 172.20.96.0/19
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 172.20.128.0/19
    name: us-east-1d
    type: Private
    zone: us-east-1d
  - cidr: 172.20.160.0/19
    name: us-east-1e
    type: Private
    zone: us-east-1e
  - cidr: 172.20.192.0/19
    name: us-east-1f
    type: Private
    zone: us-east-1f
  - cidr: 172.20.0.0/22
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 172.20.4.0/22
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 172.20.8.0/22
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  - cidr: 172.20.12.0/22
    name: utility-us-east-1d
    type: Utility
    zone: us-east-1d
  - cidr: 172.20.16.0/22
    name: utility-us-east-1e
    type: Utility
    zone: us-east-1e
  - cidr: 172.20.20.0/22
    name: utility-us-east-1f
    type: Utility
    zone: us-east-1f
  topology:
    bastion:
      bastionPublicName: bastion.dev.csye6225-fall2018-sahanip.xyz
    dns:
      type: Public
    masters: private
    nodes: private

---


apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-11-23T00:51:00Z
  labels:
    kops.k8s.io/cluster: dev.csye6225-fall2018-sahanip.xyz
  name: bastions
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-us-east-1a
  - utility-us-east-1b
  - utility-us-east-1c
  - utility-us-east-1d
  - utility-us-east-1e
  - utility-us-east-1f

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-11-23T00:50:59Z
  labels:
    kops.k8s.io/cluster: dev.csye6225-fall2018-sahanip.xyz
  name: master-us-east-1b
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  subnets:
  - us-east-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-11-23T00:50:59Z
  labels:
    kops.k8s.io/cluster: dev.csye6225-fall2018-sahanip.xyz
  name: master-us-east-1c
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-11-23T00:50:59Z
  labels:
    kops.k8s.io/cluster: dev.csye6225-fall2018-sahanip.xyz
  name: master-us-east-1d
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1d
  role: Master
  subnets:
  - us-east-1d

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-11-23T00:50:59Z
  generation: 1
  labels:
    kops.k8s.io/cluster: dev.csye6225-fall2018-sahanip.xyz
  name: nodes
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/node-template/label: ""
    kubernetes.io/cluster/dev.csye6225-fall2018-sahanip.xyz: owned
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 4
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d
  - us-east-1e
  - us-east-1f

