apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-11-17T17:40:51Z
  name: dashboard.csye6225-spring2019-murgoda.me
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://csye7374-kubernetes-cluster-state-store/dashboard.csye6225-spring2019-murgoda.me
  dnsZone: dashboard.csye6225-spring2019-murgoda.me
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: main
    version: 3.2.24
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.13.1
  masterPublicName: api.dashboard.csye6225-spring2019-murgoda.me
  networkCIDR: 172.20.0.0/16
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.20.64.0/19
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 172.20.96.0/19
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 172.20.128.0/19
    name: us-east-1d
    type: Private
    zone: us-east-1d
  - cidr: 172.20.160.0/19
    name: us-east-1e
    type: Private
    zone: us-east-1e
  - cidr: 172.20.192.0/19
    name: us-east-1f
    type: Private
    zone: us-east-1f
  - cidr: 172.20.0.0/22
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 172.20.4.0/22
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 172.20.8.0/22
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  - cidr: 172.20.12.0/22
    name: utility-us-east-1d
    type: Utility
    zone: us-east-1d
  - cidr: 172.20.16.0/22
    name: utility-us-east-1e
    type: Utility
    zone: us-east-1e
  - cidr: 172.20.20.0/22
    name: utility-us-east-1f
    type: Utility
    zone: us-east-1f
  topology:
    bastion:
      bastionPublicName: bastion.dashboard.csye6225-spring2019-murgoda.me
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-11-17T21:28:48Z
  labels:
    kops.k8s.io/cluster: dashboard.csye6225-spring2019-murgoda.me
  name: bastions
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-us-east-1a
  - utility-us-east-1b
  - utility-us-east-1c
  - utility-us-east-1d
  - utility-us-east-1e
  - utility-us-east-1f

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-11-17T21:28:48Z
  labels:
    kops.k8s.io/cluster: dashboard.csye6225-spring2019-murgoda.me
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-11-17T21:28:48Z
  labels:
    kops.k8s.io/cluster: dashboard.csye6225-spring2019-murgoda.me
  name: master-us-east-1b
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  subnets:
  - us-east-1b

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-11-17T21:28:48Z
  labels:
    kops.k8s.io/cluster: dashboard.csye6225-spring2019-murgoda.me
  name: master-us-east-1c
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-11-17T17:40:52Z
  labels:
    kops.k8s.io/cluster: dashboard.csye6225-spring2019-murgoda.me
  name: nodes
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t2.medium
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d
  - us-east-1e
  - us-east-1f
