apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: jenkins-role-binding
 namespace: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins-serviceaccount
  namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
