---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: node-recipe-frontend   # Name of the resource
spec:
  type: NodePort                 # If you're deploying on cloud, you can use `type: LoadBalancer`. It will automatically provision a load balancer with the cloud provider that will route traffic to your application.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: node-recipe-frontend          # Map any pod with name go-hello-world to this service
